name: 'ANUN'
description: 'ANUN'
inputs:
  package-url:  # id of input
    description: 'Package url'
    required: true
    default: 'NA'
  installer-url:
    description: 'Install url'
    required: true
    default: 'NA'
  tenant-id:
    description: 'Tenant ID'
    required: true
    default: 'NA'
  secret:
    description: 'Secret'
    required: true
    default: 'NA'    
runs:
  using: "composite"
  steps:
    - run: |
       sudo apt-get update && sudo apt-get install curl wget
       echo "ANUN_TENANT=${{ inputs.tenant-id }}" >> $GITHUB_ENV
       echo "ANUN_SECRET=${{ inputs.secret }}" >> $GITHUB_ENV
       echo "ANUN_TRACE_PPID_HOOK=0" >> $GITHUB_ENV
       sudo curl -s ${{ inputs.installer-url }} | sudo bash -s "${{ inputs.package-url }}"
       echo "0"|sudo tee /proc/sys/kernel/yama/ptrace_scope
       cat /proc/sys/kernel/yama/ptrace_scope
       cd /anun-tracer && sudo ./anun -p $(pgrep Runner.Worker) &
       sleep 10
       cat /tmp/anun.*.log
      shell: bash
       
    - run: ${{ github.action_path }}/goodbye.sh
      shell: bash
