name: 'ANUN'
description: 'ANUN'
inputs:
  package-url:  # id of input
    description: 'Package url'
    required: true
    default: 'NA'
  installer-url:
    description: 'Install url'
    required: true
    default: 'NA'
  tenant-id:
    description: 'Tenant ID'
    required: true
    default: 'NA'
  secret:
    description: 'Secret'
    required: true
    default: 'NA'    
runs:
  using: "composite"
  env:
      ANUN_TENANT: ${{ inputs.tenant-id }}
      ANUN_SECRET: ${{ inputs.secret }}
      ANUN_TRACE_PPID_HOOK: 0
  steps:
    - run: |
       sudo apt-get update && sudo apt-get install curl wget
       sudo curl -s ${{ inputs.installer-url }} | bash -s "${{ inputs.package-url }}" preload
      shell: bash
       
    - run: ${{ github.action_path }}/goodbye.sh
      shell: bash
