name: 'ANUN'
description: 'ANUN'
inputs:
  package-url:  # id of input
    description: 'Package url'
    required: true
    default: 'NA'
  installer-url:
    description: 'Install url'
    required: true
    default: 'NA'
  tenant-id:
    description: 'Tenant ID'
    required: true
    default: 'NA'
  secret:
    description: 'Secret'
    required: true
    default: 'NA'
  host:
    description: 'ANUN host'
    required: false
    default: 'api.anun-dev.cloud'
runs:
  using: "composite"
  steps:
    - run: |
       echo Setting up ANUN environment variables
       echo "ANUN_TENANT=${{ inputs.tenant-id }}" >> $GITHUB_ENV
       echo "ANUN_SECRET=${{ inputs.secret }}" >> $GITHUB_ENV
       echo "ANUN_SOURCE=github" >> $GITHUB_ENV
       echo "ANUN_HOST=${{ inputs.host }}" >> $GITHUB_ENV
      shell: bash
    - run: |
       echo Setting up ANUN on DOCKERIZED runner
       echo "ANUN_TRACE_PPID_HOOK=0" >> $GITHUB_ENV
       apt-get update && apt-get install curl wget
       curl -s ${{ inputs.installer-url }} | bash -s "${{ inputs.package-url }}" preload
      shell: bash
      if: ${{ job.container.id != null }}
    - run: |
       echo Setting up ANUN on HOST runner
       sudo apt-get update && sudo apt-get install curl wget
       sudo curl -s ${{ inputs.installer-url }} | sudo bash -s "${{ inputs.package-url }}"
       sudo /anun-tracer/anun -p $(pgrep Runner.Worker) &
       sleep 5
      shell: bash
      if: ${{ job.container.id == null }}
   
      
       
